name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Check if PR is from Dependabot
      id: dependabot-check
      run: |
        if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
          echo "is-dependabot=true" >> $GITHUB_OUTPUT
        else
          echo "is-dependabot=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Checkout code
      if: steps.dependabot-check.outputs.is-dependabot == 'true'
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      if: steps.dependabot-check.outputs.is-dependabot == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        
    - name: Install dependencies
      if: steps.dependabot-check.outputs.is-dependabot == 'true'
      run: npm ci
      
    - name: Run tests
      if: steps.dependabot-check.outputs.is-dependabot == 'true'
      run: npm test
      
    - name: Auto-merge minor/patch updates
      if: steps.dependabot-check.outputs.is-dependabot == 'true'
      run: |
        # Only auto-merge patch and minor updates, not major
        if echo "${{ github.event.pull_request.title }}" | grep -E "(patch|minor)" > /dev/null; then
          gh pr merge --auto --rebase
        else
          echo "Major update detected, requires manual review"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}